project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - "scripts/"
    - "data/"
    - "img/"

website:
  title: "Fostering Open Science in Linguistics"
  navbar:
    right:
      - about.qmd
      - tutorials.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

bibliography: 
  - references.bib

citation:
  container-title: "FOSIL"
google-scholar: false
